POST  http://localhost:3003/api/blogs/
Content-Type: application/json

{
    "title": "Users test",
    "author": "Momo Ylinen",
    "url": "http://www.google.com",
    "likes": 5,
    "userId": "60991bb1299662bf310ddab3"
}