POST  http://localhost:3003/api/blogs/
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IklucG9zc2libGVtb21vIiwiaWQiOiI2MDk5NGJlZWFmOTBhMmNiMmFiZTBmZmMiLCJpYXQiOjE2MjA3MzUyMzEsImV4cCI6MTYyMDczODgzMX0.xcvrSPN_53R2HZrOOwUp15hcP57NtS4-QgBuc0iFORA

{
    "title": "Go To Statement Considered Harmful",
    "author": "Edsger W. Dijkstra",
    "url": "http://www.u.arizona.edu/~rubinson/copyright_violations/Go_To_Considered_Harmful.html"
}